title: America First Podcast
theme: jekyll-theme-cayman
description: Americanism, not Globalism, will be our Credo
url: "https://americafirstpod.github.io"
image: /site_logo.jpg
podcast_description: America First Podcast with Nicholas J. Fuentes

author:
  name: "Podcast Groyper"